# See: https://www.dartlang.org/tools/pub/pubspec
name: flutter_opencv
version: 0.0.4
description: >-
  Flutter plugin for the OpenCV open-source computer vision library.
author: Arto Bendiken <arto@bendiken.net>
homepage: https://github.com/drydart/flutter_opencv
documentation:
dependencies:
  flutter:
    sdk: flutter
  flutter_android: ^0.3.2
  meta: ^1.1.6
  vector_math: ^2.0.8
  json_annotation: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.3.4 <2.0.0'
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
dependency_overrides:
environment:
  sdk: '>=2.1.0 <3.0.0'
executables:
flutter:
  plugin:
    androidPackage: com.github.drydart.flutter_opencv
    pluginClass: FlutterOpenCVPlugin
